### ISSUE TITLE
NPE when PowerAuthEncryptionProvider not autowired

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-restful-integration#156]
In case we do not autowire the `PowerAuthEncryptionProvider`, for example, because the communication with SOAP service fails, we throw NPE later:

```
2019-03-26 10:15:35,597 [undertow-worker task-5] ERROR o.s.b.w.s.support.ErrorPageFilter - Forwarding to error page from request [/pa/v3/activation/create] due to exception [null]
java.lang.NullPointerException: null
    at io.getlime.security.powerauth.rest.api.spring.annotation.PowerAuthAnnotationInterceptor.preHandle(PowerAuthAnnotationInterceptor.java:89)
    at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:136)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:986)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:884)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
```

We should probably capture this situation a bit better in logs.

**Comment by romanstrobl** [comment]
I cannot reproduce the issue neither in release `0.21.0` nor in `develop` branch. My suspicion is that the issue is casued by backend built against non-release version of restful-integration (e.g. some older commit before release `0.21.0` which had an NPE in class `PowerAuthEncryptionProvider` or `PowerAuthEncryptionProviderBase`).

See exception from release `0.21.0` when obtaining ECIES decryptor fails.

[exception_release.txt](https://github.com/wultra/powerauth-restful-integration/files/3008649/exception_release.txt)

I will keep the issue open until we confirm that deploying backend built against release fixes the issue.

**Comment by romanstrobl** [comment]
The issue was caused by invalid Spring configuration of component which used restful-integration as a dependency.
